---

- block:
    - name: Copy systemd unit file
      template:
        src: prometheus-kafka-adapter.service.j2
        dest: "/etc/systemd/system/prometheus-kafka-adapter-{{ prometheus_kafka_adapter_container_name }}.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart prometheus-kafka-adapter

    - name: Create systemd config dir
      file:
        path: "/etc/systemd/system/prometheus-kafka-adapter-{{ prometheus_kafka_adapter_container_name }}.service.d/"
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: Copy systemd unit environment file
      template:
        src: env.conf.j2
        dest: "/etc/systemd/system/prometheus-kafka-adapter-{{ prometheus_kafka_adapter_container_name }}.service.d/local.conf"
        owner: root
        group: root
        mode: 0644
      notify:
        - Restart prometheus-kafka-adapter

    - name: Start and enable
      become: true
      systemd:
        name: "prometheus-kafka-adapter-{{ prometheus_kafka_adapter_container_name }}"
        state: started
        enabled: yes
      ignore_errors: '{{ ansible_check_mode }}'
