---

- block:
    - name: Copy systemd unit file
      template:
        src: prometheus-kafka-adapter.service.j2
        dest: "/etc/systemd/system/prometheus-kafka-adapter-{{ prometheus_kafka_adapter_container_name }}.service"
        owner: root
        group: root
        mode: 0644
      register: systemd_unit

    - name: Create systemd config dir
      file:
        path: "/etc/systemd/system/prometheus-kafka-adapter-{{ prometheus_kafka_adapter_container_name }}.service.d/"
        state: directory
        owner: root
        group: root
        mode: 0644
      register: config_dir

    - name: Copy systemd unit environment file
      template:
        src: env.conf.j2
        dest: "/etc/systemd/system/prometheus-kafka-adapter-{{ prometheus_kafka_adapter_container_name }}.service.d/local.conf"
        owner: root
        group: root
        mode: 0644
      register: systemd_unit_env

    - name: Start and enable
      become: true
      systemd:
        name: "prometheus-kafka-adapter-{{ prometheus_kafka_adapter_container_name }}"
        state: started
        enabled: yes

    - name: restart prometheus-kafka-adapter
      become: true
      systemd:
        daemon_reload: true
        name: "prometheus-kafka-adapter-{{ prometheus_kafka_adapter_container_name }}"
        state: restarted
      when: systemd_unit.changed or config_dir.changed or systemd_unit_env.changed

