---
- name: Pull image
  docker_image:
    name: "{{ prometheus_kafka_adapter_docker_image }}"
    source: pull

- block:
    - name: Copy systemd unit file
      template:
        src: prometheus-kafka-adapter.service.j2
        dest: /etc/systemd/system/prometheus-kafka-adapter.service
        owner: root
        group: root
        mode: 0644
      notify: restart prometheus-kafka-adapter

    - name: Create systemd config dir
      file:
        path: /etc/systemd/system/prometheus-kafka-adapter.service.d/
        state: directory
        owner: root
        group: root
        mode: 0644

    - name: Copy systemd unit environment file
      template:
        src: env.conf.j2
        dest: /etc/systemd/system/prometheus-kafka-adapter.service.d/local.conf
        owner: root
        group: root
        mode: 0644
      notify: restart prometheus-kafka-adapter

- name: Create general config dir
  file:
    path: "{{ prometheus_kafka_adapter_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0644

- name: Copy client cert file
  copy:
    src: "{{ prometheus_kafka_adapter_tls_client_cert_file }}"
    dst: "{{ prometheus_kafka_adapter_config_dir }}/client-cert.pem"
    owner: root
    group: root
    mode: '0600'
  when: prometheus_kafka_adapter_tls_client_cert_file != ""
  notify: restart prometheus-kafka-adapter

- name: Start and enable
  systemd:
    name: prometheus-kafka-adapter
    state: started
    enabled: yes