---
- name: Install python dependencies
  block:
    - name: Install python dependencies via pip
      pip:
        name:
          - "requests==2.20.0"
          - "docker==4.2.1"
        state: present
      when: prometheus_kafka_adapter_manage_pip_packages
      
    - name: Install python dependencies via yum
      yum:
        name:
          - python3-docker
          - python3-requests
        state: present
      when: prometheus_kafka_adapter_manage_yum_packages

- name: prometheus_kafka_adapter | log into docker registry
  docker_login:
    registry: "{{ prometheus_kafka_adapter_docker_registry }}"
    username: "{{ prometheus_kafka_adapter_docker_username }}"
    password: "{{ prometheus_kafka_adapter_docker_password }}"
  when:
    - prometheus_kafka_adapter_docker_username != ''
    - prometheus_kafka_adapter_docker_password != ''

- name: Pull image
  docker_image:
    name: "{{prometheus_kafka_adapter_docker_registry}}/{{ prometheus_kafka_adapter_docker_image }}"
    source: pull

- name: Configure kafka container as systemd services
  vars:
    prometheus_kafka_adapter_container_name: "{{ config_list.name }}"
    prometheus_kafka_adapter_listen_port: "{{ config_list.listen_port }}"
    prometheus_kafka_adapter_log_level: "{{ config_list.log_level }}"
    prometheus_kafka_adapter_kafka_topic: "{{ config_list.kafka_topic }}"
    prometheus_kafka_adapter_gin_mode: "{{ config_list.gin_mode }}"
    prometheus_kafka_adapter_kafka_broker_list: "{{ config_list.kafka_broker_list }}"

  include_tasks: configure_systemd.yml
  loop:
    "{{ prometheus_kafka_adapter_config_list }}"
  loop_control:
    loop_var: config_list
