Vagrant.configure("2") do |config| 
    config.vm.provider "virtualbox" do |vb| 
        vb.memory = "1024" 
        vb.cpus = "1"
    end

    # CentOS 8 VM
    config.vm.define "centos8" do |centos|
      centos.vm.box = "centos/8"
      centos.vm.provider "virtualbox" do |vb|
      end
    end
 
     # RHEL 7 VM
    config.vm.define "rhel7" do |centos|
      centos.vm.box = "generic/rhel7"
      centos.vm.provider "virtualbox" do |vb|
      end
    end

     # RHEL 8 VM
    config.vm.define "rhel8" do |centos|
      centos.vm.box = "generic/rhel8"
      centos.vm.provider "virtualbox" do |vb|
      end
    end

    # Debian 9 VM
    config.vm.define "debian9" do |debian|
      debian.vm.box = "debian/stretch64"
      debian.vm.provider "virtualbox" do |vb|
      end
    end

    # Debian 10 VM
    config.vm.define "debian10" do |debian|
      debian.vm.box = "debian/buster64"
      debian.vm.provider "virtualbox" do |vb|
      end
    end

    # Ubuntu 18.04 VM
    config.vm.define "ubuntu1804" do |debian|
      debian.vm.box = "ubuntu/bionic64"
      debian.vm.provider "virtualbox" do |vb|
      end
    end

    # Ubuntu 20.04 VM
    config.vm.define "ubuntu2004" do |debian|
      debian.vm.box = "ubuntu/focal64"
      debian.vm.provider "virtualbox" do |vb|
      end
    end

    config.vm.provision "ansible" do |ansible|
        ansible.become = true
        ansible.verbose = "v"
        ansible.playbook = "test.yml"
        #ansible.groups = {
        #}
        #ansible.host_vars = {
        #}
    end
end
